// Generated by CoffeeScript 1.7.1
angular.module('angular-beacon', []).directive('beacon', function() {
  return {
    restrict: 'E',
    link: function(scope, element, attributes) {
      var cached, domCheck, elapsedTime, missing, name;
      console.assert(attributes.waitfor, "The 'beacon' directive expects the 'waitfor' attribute.");
      console.assert(attributes.onready, "The 'beacon' directive expects the 'onready' attribute.");
      missing = (function() {
        var _i, _len, _ref, _results;
        _ref = attributes.waitfor.split(',');
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          name = _ref[_i];
          _results.push(name.trim());
        }
        return _results;
      })();
      cached = [];
      elapsedTime = 0;
      domCheck = function() {
        var found, i, selector, _i, _len;
        for (i = _i = 0, _len = missing.length; _i < _len; i = ++_i) {
          selector = missing[i];
          found = $(selector);
          if (found.length > 0) {
            cached[i] = found;
            missing.splice(i, 1);
          }
        }
        if (elapsedTime >= 5000) {
          return console.warn('Timeout reached. Bailing out.');
        } else if (missing.length > 0) {
          elapsedTime += 25;
          return setTimeout(domCheck, 25);
        } else {
          return scope[attributes.onready].call(null, cached);
        }
      };
      return domCheck();
    }
  };
});
